/* eslint-disable react/no-unescaped-entities */
import { Box } from "@chakra-ui/react"
import React from "react"

import AppLayout from "../components/AppLayout"
const PrivacyPage = () => {
  return (
    <AppLayout>
      <Box h="100%" w="100%" bg="page.background" color="page.text" p="12">
        <Box as="section" maxW="5xl" mx="auto" py="12" px={{ base: "6", md: "8" }}>
          <strong>TERMS OF SALE</strong>
          <br />
          <p dir="ltr">for the Online Sale of Goods and Services</p>
          <br />
          <p dir="ltr">
            THIS DOCUMENT CONTAINS VERY IMPORTANT INFORMATION REGARDING YOUR RIGHTS AND OBLIGATIONS,
            AS WELL AS CONDITIONS, LIMITATIONS, AND EXCLUSIONS THAT MIGHT APPLY TO YOU. PLEASE READ
            IT CAREFULLY.
          </p>
          <br />
          <p dir="ltr">
            THESE TERMS REQUIRE THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES,
            RATHER THAN JURY TRIALS OR CLASS ACTIONS.
          </p>
          <br />
          <p dir="ltr">
            BY PLACING AN ORDER FOR PRODUCTS OR SERVICES FROM THIS WEBSITE, YOU AFFIRM THAT YOU ARE
            OF LEGAL AGE TO ENTER INTO THIS AGREEMENT, AND YOU ACCEPT AND ARE BOUND BY THESE TERMS
            AND CONDITIONS. YOU AFFIRM THAT IF YOU PLACE AN ORDER ON BEHALF OF AN ORGANIZATION OR
            COMPANY, YOU HAVE THE LEGAL AUTHORITY TO BIND ANY SUCH ORGANIZATION OR COMPANY TO THESE
            TERMS AND CONDITIONS.
          </p>
          <br />
          <p dir="ltr">
            YOU MAY NOT ORDER OR OBTAIN PRODUCTS OR SERVICES FROM THIS WEBSITE IF YOU (A) DO NOT
            AGREE TO THESE TERMS, (B) ARE NOT THE OLDER OF (i) AT LEAST 18 YEARS OF AGE OR (ii)
            LEGAL AGE TO FORM A BINDING CONTRACT WITH NEXTNAME, OR (C) ARE PROHIBITED FROM ACCESSING
            OR USING THIS WEBSITE OR ANY OF THIS WEBSITE'S CONTENTS, GOODS OR SERVICES BY APPLICABLE
            LAW.
          </p>
          <br />
          <p dir="ltr">
            These terms and conditions (these "Terms") apply to the purchase and sale of products
            and services through https://www.NextName.io (the "Site"). These Terms are subject to
            change by ILL-NFT, Inc., an Illinois corporation, doing business as NextName (referred
            to as “NextName”, "us", "we", or "our" as the context may require) without prior written
            notice at any time, in our sole discretion. Any changes to the Terms will be in effect
            as of the "Last Updated Date" referenced on the Site. You should review these Terms
            prior to purchasing any product or services that are available through this Site. Your
            continued use of this Site after the "Last Updated Date" will constitute your acceptance
            of and agreement to such changes.
          </p>
          <p dir="ltr">
            These Terms are an integral part of the Website Terms of Use that apply generally to the
            use of our Site. You should also carefully review our Privacy Policy before placing an
            order for products or services through this Site (see Section 9).
          </p>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Products and Services. The Company’s products and services currently include the
                following products:
              </p>
            </li>
            <ol>
              <li dir="ltr">
                <p dir="ltr">
                  Digital Collectibles. The Company sells “Digital Collectibles” which means
                  non-fungible tokens (“NFTs”) generated by the Company, and its contractors, and
                  displayed on the Company’s Website as well as other third party websites. The
                  Company’s Digital Collectibles reside on the Flow Blockchain platform (the “Flow
                  Network”). The Company’s Digital Collectibles are created through the use of a
                  smart contract that is entered into between the Company and a “Hosting Service”.
                  The Company currently uses the following Hosting Services and all Digital
                  Collectibles sold using a Hosting Service are subject to the additional terms and
                  conditions of such Hosting Service which are set forth below:
                </p>
              </li>
              <ol>
                <li dir="ltr">
                  <p dir="ltr">Niftory, Inc.</p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">Rarible, Inc.</p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">Ozone Networks, Inc. d/b/a OpenSea</p>
                </li>
              </ol>
              <li dir="ltr">
                <p dir="ltr">
                  Licenses Granted. The Company grants to the buyer of a Digital Collectible, and
                  its successors and assigns, the following rights subject to the Terms of Use and
                  these Terms:
                </p>
              </li>
              <ol>
                <li dir="ltr">
                  <p dir="ltr">
                    Upon payment in full for a Digital Collectible, the buyer, and its’ successors
                    and assigns, shall during their period of ownership of the Digital Collectible
                    have a non-exclusive, royalty-free, fully paid, worldwide, sublicensable,
                    revocable license to store, use, distribute, and display the Digital
                    Collectible, in any and all media, such as on social media platforms, either now
                    known or hereinafter invented or devised;
                  </p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">
                    Unless an Endorsement Use is granted in connection with the sale of a Digital
                    Collectible, an owner may only use a Digital Collectible for their own personal,
                    non-commercial, and non-promotional use, and subject to these Terms;
                  </p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">
                    You may not alter, modify, or change, the contents of any Digital Collectible.
                  </p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">
                    An “Endorsement Use” is a token that is sold to a business for the purpose of
                    providing a business endorsement. An Endorsement Use shall be subject to the
                    terms and conditions of the endorsement concerning the duration, use, and other
                    terms, set forth at the time of sale.
                  </p>
                </li>
              </ol>
              <li dir="ltr">
                <p dir="ltr">
                  Fees. Buying, selling or transferring Digital Collectibles may be subject to fees,
                  commissions, royalties and other charges (“Fees”) established from time to time in
                  the sole discretion of the Company, a Hosting Service, a Digital Wallet, a Payment
                  Processor, or other third party service provider. On the date of initial
                  publication of these Terms, Fees include: (a) service fees established by and
                  payable to the Company; (b) commissions on secondary sales of Digital
                  Collectibles, established by and payable to the creators of such Digital
                  Collectibles; (c) “gas” (fees paid to the Flow Network for the use of their
                  network); and (d) transaction fees charged by the Hosting Service. Fees may be
                  adjusted from time to time in the sole discretion of the Company and the third
                  party providing such services. Commissions are set in the sole discretion of the
                  Company and may range from 0% to 100%; in the event that a User acquires a Digital
                  Collectible with a 100% commission, the User will be unable to collect any
                  proceeds of a sale of that Digital Collectible on the Company’s platform. “Gas”
                  fees are set by the User through the User’s independent Digital Wallet
                  application, based on the market conditions. Unless otherwise set forth at the
                  time of sale, a ten percent (10%) commission shall apply to any resale of a
                  Digital Collectible.
                </p>
              </li>
              <li dir="ltr">
                <p dir="ltr">
                  Digital Wallets. Digital Collectibles purchased on the Company’s Website can be
                  accessed and displayed through a third-party digital wallet provider that may be
                  downloaded on, or linked to, the Company’s Website (“Digital Wallet”). Wallets are
                  not operated by the Company and the Company will have no control over the contents
                  of your Digital Wallet, or any ability to retrieve or transfer its contents. The
                  Company has no responsibility for, or liability to you, in connection with your
                  use of a Digital Wallet and makes no representations or warranties regarding how
                  the our service will operate with any specific Digital Wallet. You are solely
                  responsible for keeping your Digital Wallet secure and you should never share your
                  Digital Wallet credentials or seed phrase with anyone. If you discover an issue
                  related to your Digital Wallet, please contact your Digital Wallet provider.
                  Likewise, you are solely responsible for your user account with us and any
                  associated Digital Wallet and we are not liable for any acts or omissions by you
                  in connection with your user account or as a result of your user account or
                  Digital Wallet being compromised. You agree to immediately notify us if you
                  discover or otherwise suspect any security issues related to our service or your
                  user account.
                </p>
              </li>
              <li dir="ltr">
                <p dir="ltr">
                  Infringement Claims. In the event that a Digital Collectible purchased on our
                  Website becomes the subject of an infringement or other legal claim, including but
                  not limited to a copyright, trademark, or patent infringement (an “IP Claim”), a
                  claim for the misappropriation of a person’s name, image, voice, or likeness (an
                  “NIL Claim”), or any other legal claim (an “Other Legal Claim”), the Company shall
                  have the right to terminate all licensing rights granted pursuant to these Terms
                  and may require any owner of the Digital Collectible to destroy or “burn” such
                  Digital Collectible by posting written notice of the termination of rights on the
                  Company’s Website (“Notice of Termination of Rights”). The Company may offer, but
                  shall not be legally required to offer, a refund to the owner of such Digital
                  Collectible upon the transfer of such Digital Collectible to the Company. Any
                  owner of a Digital Collectible that continues to store, use, distribute, transfer,
                  or display such Digital Collectible following publication of such Notice of
                  Termination of Rights shall be liable to the Company for such use, distribution,
                  transfer, or display of such Digital Collectible.
                </p>
              </li>
            </ol>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Order Acceptance and Cancellation. You agree that your order is an offer to buy,
                under these Terms, all products and services listed in your order. All orders must
                be accepted by us or we will not be obligated to sell the products or services to
                you. We may choose not to accept orders at our sole discretion, even after we send
                you a confirmation email with your order number and details of the items you have
                ordered.
              </p>
            </li>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">Prices and Payment Terms.</p>
            </li>
            <ol>
              <li dir="ltr">
                <p dir="ltr">
                  Prices posted on this Site may be different than prices offered by us on other
                  Hosting Services. All prices, discounts, and promotions posted on this Site are
                  subject to change without notice. The price charged for a product or service will
                  be the price in effect at the time the order is placed and will be set out in your
                  order confirmation email. Price increases will only apply to orders placed after
                  such changes. Posted prices do not include taxes or charges for shipping and
                  handling. All such taxes and charges will be added to your merchandise total, and
                  will be itemized in your shopping cart and in your order confirmation email. We
                  strive to display accurate price information, however we may, on occasion, make
                  inadvertent typographical errors, inaccuracies or omissions related to pricing and
                  availability. We reserve the right to correct any errors, inaccuracies, or
                  omissions at any time and to cancel any orders arising from such occurrences.
                </p>
              </li>
              <li dir="ltr">
                <p dir="ltr">
                  We may offer from time to time promotions on the Site that may affect pricing and
                  that are governed by terms and conditions separate from these Terms. If there is a
                  conflict between the terms for a promotion and these Terms, the promotion terms
                  will govern.
                </p>
              </li>
              <li dir="ltr">
                <p dir="ltr">
                  The following terms may be used by us to communicate pricing information:
                </p>
              </li>
              <ol>
                <li dir="ltr">
                  <p dir="ltr">
                    "Bid Price" references a price being offered in connection with the auction of
                    our product or service and is not a final price, but rather an offer to purchase
                    at that price subject to other Users making higher offers to purchase the
                    product or service.
                  </p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">
                    "Fixed Price" references our normal price for a product or service.
                  </p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">"Sale" refers to a reduced price for a product or service.</p>
                </li>
                <li dir="ltr">
                  <p dir="ltr">
                    "Clearance" refers to a reduced price for a product or service that will be
                    discontinued.
                  </p>
                </li>
              </ol>
              <li dir="ltr">
                <p dir="ltr">
                  Terms of payment are within our sole discretion and, unless otherwise agreed by us
                  in writing, payment must be received by us before our acceptance of an order. We
                  use a third party payment processing company [(Stripe)] for sales of our products
                  and services. You represent and warrant that (i) the credit card information you
                  supply to us is true, correct and complete, (ii) you are duly authorized to use
                  such credit card for the purchase, (iii) charges incurred by you will be honored
                  by your credit card company, and (iv) you will pay charges incurred by you at the
                  posted prices, including shipping and handling charges and all applicable taxes,
                  if any, regardless of the amount quoted on the Site at the time of your order.
                </p>
              </li>
            </ol>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">Shipments; Delivery; Title and Risk of Loss.</p>
            </li>
            <ol>
              <li dir="ltr">
                <p dir="ltr">
                  We will arrange for the delivery of the products to you. Please check the
                  individual product page for specific delivery options. You will pay all shipping
                  and handling charges of any tangible products specified during the ordering
                  process. Shipping and handling charges are reimbursement for the costs we incur in
                  the processing, handling, packing, shipping, and delivery of your order.
                </p>
              </li>
              <li dir="ltr">
                <p dir="ltr">
                  Title and risk of loss pass to you upon our transfer of the products to the
                  carrier/delivery. Shipping and delivery dates are estimates only and cannot be
                  guaranteed. We are not liable for any delays in shipments.
                </p>
              </li>
            </ol>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Returns and Refunds. Except for products containing a material defect, all product
                and service sales are final and may not be returned to the Company for a refund.
              </p>
            </li>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Warranty and Disclaimers. The availability of products or services through our Site
                does not indicate an affiliation with or endorsement of any person, company,
                product, service or other party. Accordingly, we do not provide any warranties with
                respect to the products or services offered on our Site.
              </p>
            </li>
          </ol>
          <br />
          <p dir="ltr">
            ALL PRODUCTS AND SERVICES OFFERED ON THIS SITE ARE PROVIDED “AS IS” WITHOUT ANY WARRANTY
            WHATSOEVER, INCLUDING, WITHOUT LIMITATION, ANY (A) WARRANTY OF MERCHANTABILITY; (B)
            WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; OR (C) WARRANTY AGAINST INFRINGEMENT OF
            INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER EXPRESS OR IMPLIED BY LAW, COURSE
            OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE.
          </p>
          <p dir="ltr">
            SOME JURISDICTIONS LIMIT OR DO NOT ALLOW THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES
            SO THE ABOVE DISCLAIMER MAY NOT APPLY TO YOU.
          </p>
          <p dir="ltr">
            YOU AFFIRM THAT WE SHALL NOT BE LIABLE, UNDER ANY CIRCUMSTANCES, FOR ANY BREACH OF
            WARRANTY CLAIMS OR FOR ANY DAMAGES ARISING OUT OF THE MANUFACTURER'S FAILURE TO HONOR
            ITS WARRANTY OBLIGATIONS TO YOU.
          </p>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Limitation of Liability. WE HAVE BEEN GIVEN ASSURANCES OF PRODUCT SALABILITY,
                MERCHANTIBILITY, AND COMPLIANCE FROM THE MANUFACTURERS.] IN NO EVENT SHALL WE BE
                LIABLE TO YOU OR ANY THIRD PARTY FOR CONSEQUENTIAL, INDIRECT, INCIDENTAL, SPECIAL,
                EXEMPLARY, PUNITIVE OR ENHANCED DAMAGES, LOST PROFITS OR REVENUES OR DIMINUTION IN
                VALUE, ARISING OUT OF, OR RELATING TO, AND/OR IN CONNECTION WITH ANY BREACH OF THESE
                TERMS, REGARDLESS OF (A) WHETHER SUCH DAMAGES WERE FORESEEABLE, (B) WHETHER OR NOT
                WE WERE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND (C) THE LEGAL OR EQUITABLE
                THEORY (CONTRACT, TORT OR OTHERWISE) UPON WHICH THE CLAIM IS BASED.
              </p>
            </li>
          </ol>
          <br />
          <p dir="ltr">
            OUR SOLE AND ENTIRE MAXIMUM LIABILITY, FOR ANY REASON, AND YOUR SOLE AND EXCLUSIVE
            REMEDY FOR ANY CAUSE WHATSOEVER, SHALL BE LIMITED TO THE ACTUAL AMOUNT PAID BY YOU FOR
            THE PRODUCTS AND SERVICES YOU HAVE ORDERED THROUGH OUR SITE.
          </p>
          <br />
          <p dir="ltr">
            The limitation of liability set forth above shall: (i) only apply to the extent
            permitted by law and (ii) not apply to (A) liability resulting from our gross negligence
            or willful misconduct and (B) death or bodily injury resulting from our acts or
            omissions.
          </p>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Goods Not for Resale or Export. You represent and warrant that you are buying
                products or services from the Site for your own personal or household use only, and
                not for resale or export. You further represent and warrant that all purchases are
                intended for final delivery to locations within the US.
              </p>
            </li>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Privacy. We respect your privacy and are committed to protecting it. Our Privacy
                Policy found at http//:www.nextname.io/privacy policy, governs the processing of all
                personal data collected from you in connection with your purchase of products or
                services through the Site.
              </p>
            </li>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Force Majeure. We will not be liable or responsible to you, nor be deemed to have
                defaulted or breached these Terms, for any failure or delay in our performance under
                these Terms when and to the extent such failure or delay is caused by or results
                from acts or circumstances beyond our reasonable control, including, without
                limitation, acts of God, flood, fire, earthquake, explosion, governmental actions,
                war, invasion or hostilities (whether war is declared or not), terrorist threats or
                acts, riot or other civil unrest, national emergency, revolution, insurrection,
                epidemic, lockouts, strikes or other labor disputes (whether or not relating to our
                workforce), or restraints or delays affecting carriers or inability or delay in
                obtaining supplies of adequate or suitable materials, materials or telecommunication
                breakdown or power outage.
              </p>
            </li>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Governing Law and Jurisdiction. This Site is operated from the US. All matters
                arising out of or relating to these Terms are governed by and construed in
                accordance with the internal laws of the State of Illinois without giving effect to
                any choice or conflict of law provision or rule (whether of the State of Illinois or
                any other jurisdiction) that would cause the application of the laws of any
                jurisdiction other than those of the State of Illinois.
              </p>
            </li>
          </ol>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">Dispute Resolution and Binding Arbitration.</p>
            </li>
            <ol>
              <li dir="ltr">
                <p dir="ltr">
                  YOU AND NEXTNAME, ARE AGREEING TO GIVE UP ANY RIGHTS TO LITIGATE CLAIMS IN A COURT
                  OR BEFORE A JURY, OR TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE ACTION
                  WITH RESPECT TO A CLAIM. OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT MAY
                  ALSO BE UNAVAILABLE OR MAY BE LIMITED IN ARBITRATION.
                </p>
              </li>
            </ol>
          </ol>
          <br />
          <p dir="ltr">
            ANY CLAIM, DISPUTE OR CONTROVERSY (WHETHER IN CONTRACT, TORT OR OTHERWISE, WHETHER
            PRE-EXISTING, PRESENT OR FUTURE, AND INCLUDING STATUTORY, CONSUMER PROTECTION, COMMON
            LAW, INTENTIONAL TORT, INJUNCTIVE AND EQUITABLE CLAIMS) BETWEEN YOU AND US ARISING FROM
            OR RELATING IN ANY WAY TO YOUR PURCHASE OF PRODUCTS OR SERVICES THROUGH THE SITE, WILL
            BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION.
          </p>
          <br />
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                The arbitration will be administered by the American Arbitration Association ("AAA")
                in accordance with the Consumer Arbitration Rules (the "AAA Rules") then in effect,
                except as modified by this Section 12. (The AAA Rules are available at
                www.adr.org/arb_med or by calling the AAA at 1-800-778-7879.) The Federal
                Arbitration Act will govern the interpretation and enforcement of this section.
              </p>
            </li>
          </ol>
          <br />
          <br />
          <p dir="ltr">
            The arbitrator will have exclusive authority to resolve any dispute relating to
            arbitrability and/or enforceability of this arbitration provision, including any
            unconscionability challenge or any other challenge that the arbitration provision or the
            agreement is void, voidable, or otherwise invalid. The arbitrator will be empowered to
            grant whatever relief would be available in court under law or in equity. Any award of
            the arbitrator(s) will be final and binding on each of the parties, and may be entered
            as a judgment in any court of competent jurisdiction.
          </p>
          <p dir="ltr">
            We will be responsible for paying any individual consumer's arbitration fees/If you
            prevail on any claim that affords the prevailing party attorneys' fees, the arbitrator
            may award reasonable fees to you under the standards for fee shifting provided by law.
          </p>
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                You may elect to pursue your claim in small-claims court rather than arbitration if
                you provide us with written notice of your intention do so within 60 days of your
                purchase. The arbitration or small-claims court proceeding will be limited solely to
                your individual dispute or controversy.
              </p>
            </li>
            <li dir="ltr">
              <p dir="ltr">
                You agree to an arbitration on an individual basis. In any dispute, NEITHER YOU NOR
                NEXTNAME WILL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS BY OR AGAINST OTHER
                CUSTOMERS IN COURT OR IN ARBITRATION OR OTHERWISE PARTICIPATE IN ANY CLAIM AS A
                CLASS REPRESENTATIVE, CLASS MEMBER OR IN A PRIVATE ATTORNEY GENERAL CAPACITY. The
                arbitral tribunal may not consolidate more than one person's claims, and may not
                otherwise preside over any form of a representative or class proceeding. The
                arbitral tribunal has no power to consider the enforceability of this class
                arbitration waiver and any challenge to the class arbitration waiver may only be
                raised in a court of competent jurisdiction.
              </p>
            </li>
          </ol>
          <br />
          <p dir="ltr">
            If any provision of this arbitration agreement is found unenforceable, the unenforceable
            provision will be severed and the remaining arbitration terms will be enforced.
          </p>
          <ol>
            <li dir="ltr">
              <p dir="ltr">
                Assignment. You will not assign any of your rights or delegate any of your
                obligations under these Terms without our prior written consent. Any purported
                assignment or delegation in violation of this Section 13 is null and void. No
                assignment or delegation relieves you of any of your obligations under these Terms.
              </p>
            </li>
            <li dir="ltr">
              <p dir="ltr">
                No Waivers. The failure by us to enforce any right or provision of these Terms will
                not constitute a waiver of future enforcement of that right or provision. The waiver
                of any right or provision will be effective only if in writing and signed by a duly
                authorized representative of NextName.
              </p>
            </li>
            <li dir="ltr">
              <p dir="ltr">
                No Third-Party Beneficiaries. These Terms do not and are not intended to confer any
                rights or remedies upon any person other than you.
              </p>
            </li>
            <li dir="ltr">
              <p dir="ltr">Notices.</p>
            </li>
            <ol>
              <li dir="ltr">
                <p dir="ltr">
                  To You. We may provide any notice to you under these Terms by: (i) sending a
                  message to the email address you provide or (ii) by posting to the Site. Notices
                  sent by email will be effective when we send the email and notices we provide by
                  posting will be effective upon posting. It is your responsibility to keep your
                  email address current.
                </p>
              </li>
              <li dir="ltr">
                <p dir="ltr">
                  To Us. To give us notice under these Terms, you must contact us as follows: (i) by
                  personal delivery, overnight courier, or registered or certified mail to
                  [legal@nextname.io]. We may update the address for notices to us by posting a
                  notice on the Site. Notices provided by personal delivery or email will be
                  effective upon receipt. Notices provided by overnight courier will be effective
                  one business day after they are sent. Notices provided by registered or certified
                  mail will be effective three business days after they are sent.
                </p>
              </li>
            </ol>
            <li dir="ltr">
              <p dir="ltr">
                Severability. If any provision of these Terms is invalid, illegal, void or
                unenforceable, then that provision will be deemed severed from these Terms and will
                not affect the validity or enforceability of the remaining provisions of these
                Terms.
              </p>
            </li>
            <li dir="ltr">
              <p dir="ltr">
                Entire Agreement. These Terms, the license agreement relating to any product or
                service you obtain on or through this Site, our Website [Terms of Use] and our
                [Privacy Policy] will be deemed the final and integrated agreement between you and
                us on the matters contained in these Terms.
              </p>
            </li>
          </ol>
          <br />
          <br />
        </Box>
      </Box>
    </AppLayout>
  )
}
export default PrivacyPage
